### ISSUE TITLE
Some small points about your .vcf handling scripts.

### ISSUE THREAD

**Issue by pe1aqp** [vermaden/scripts#14]
I'm very happy to have found your .vcf file handling scripts. Thank you!
At last a way to manage the contact from my phones in a "unixy" way!

I have a few (minor !) comments on the code:

1. The "sed" instructions to remove CR (a.k.a. ^M or "\r") are not reliable.
    I don't fully understand why it sometimes seem to work and sometimes fails.
    Perhaps something with different versions of sed ? or different shells (bash, bsd-sh) ?
    But, since CR is extremely unlike to occur elsewhere, I modified the sed instruction to remove CR everywhere.
    Drop the dollar symbol.
```
    sed -e s/$'\r'//g \    ===>  sed -e s/'\r'//g \
```
2. I have something similar, but slightly different, to your usage counter at the end of the scripts.
    I would suggest that you protect those lines with a test to see if the directory exists.
    Something like:
```
    if [ -d ~/scripts/stats/ ] ; then echo '1' 2> /dev/null >> ~/scripts/stats/${0##*/} ; fi
```
3. In the script "contacts-convert-vcf-from.sh" there are two "funny" assignment:
    line 100 (as in current github display):
         MAIL=""
    line 119:
        TEL=""

    Both these variables do not occur elsewhere in the file, some similarly named variables do occur.
    This looks to me remnants of earlier versions of the file.

Again: Thanks for these scripts.
Best Regards.

**Comment by vermaden** [comment]
Hi,

> I'm very happy to have found your .vcf file handling scripts. Thank you!

That makes You number 'two' user of them, welcome :)

AD. 1.

I just removed the '$' symbol from the sed(1) command in both scripts.

AD. 2.

I wanted to check some stats on my scripts - now I do not 'gather' these stats anymore - so I just removed them from GitHub repo scripts.

AD. 3.

You are right - probably some leftovers when I wrote them - removed and committed to the GitHub repo.

Thank You for taking the time to report these issues :)

Regards,
ver
