### ISSUE TITLE
Pipe the output of `contacts-convert-vcf-from.sh` through `uniq`.

### ISSUE THREAD

**Issue by pe1aqp** [vermaden/scripts#17]
I have two telephones, with mainly the same contacts (the newer phone was of course seeded with the data from the older one). Over time the contacts developed differences; but still many contacts are exactly the same.

When attempting to convert these into one common data file, using the `contacts-convert-vcf-from.sh` and `contacts-check.sh`, there are many lines that I have to remove by hand.

I find a better approach to first concatenate the ".vcf" files from both phones, process the combined file with `contacts-convert-vcf-from.sh` and run the out through `uniq`.  Something like:

```
cat contacts-ph1.vcf contacts-ph2.vcf > combined.vcf
contacts-convert-vcf-from.sh -p combined.vcf | uniq > combined.txt
```
I think that it would make sense to include this call to `uniq` in the `contacts-convert-vcf-from.sh` script.
```
$ diff -C 3 contacts-from-vcf.sh contacts-from-vcf.sh-original
*** contacts-from-vcf.sh	2024-08-11 12:59:18.798498886 +0200
--- contacts-from-vcf.sh-original	2024-08-11 13:21:00.899107133 +0200
***************
*** 217,220 ****
  	    ;;
  	
        esac
!     done | sort -n | uniq
--- 217,220 ----
  	    ;;
  	
        esac
!     done | sort -n
```
Perhaps add `--ignore-case` to the `uniq` call, but that will do little in practice, I guess.

**Comment by vermaden** [comment]
Hi,

thank You for all these findings.

I have made an update/commit according to Your suggestions.

Details here:
https://github.com/vermaden/scripts/commit/e6208052b58d2b658138c1fc9631e69686399cd4

Let me know it this is what You had in mind.

Regards,
ver

**Comment by pe1aqp** [comment]
Uniq is Fixed. Some comments with issue #15.

**Comment by MirLach** [comment]
Just a small optimization - when using `sort`, there is no need to add another pipe to `uniq`, just add `-u` to `sort` and save some system resources.
