### ISSUE TITLE
Spaces in notes are lost when re-creating a `.vcf` file.

### ISSUE THREAD

**Issue by pe1aqp** [vermaden/scripts#18]
The script `contacts-convert-vcf-from.sh` converts spaces in `NOTE` fields to semicolons.  But the script `contacts-convert-vcf-to.sh` does not restore those spaces.

The simplest fix is of course to add `| tr ';' ' ' ` to the echo-ing of `${vNOTE}`  in `contacts-convert-vcf-to.sh`. 

But this has the disadvantage that semicolons in the original note-text are also converted to spaces.

My telephone saves semicolons from the original note-text as escaped symbol pairs: `"\;"`, but this backslash is discarded by by the very first processing step, and by almost any following step.  (Re-)escaping these semicolons with backslashes in `contacts-convert-vcf-from.sh` is therefore also tricky, you need a backslash(-pair) for almost any subsequent processing.  Better is to use another character, one that is not commonly used as escape character, one that is not used very often and that is extremely unlikely to be used in combination with a semicolon. Tilde `"~"` seems a good candidate.

Together this implies changes in two scripts:

In `contacts-convert-vcf-from.sh`. First replace existing semicolons with tilde-escaped-semicolon, then replace all spaces with semicolons:
```
    # (NOTE*)     #### ALSO remove the (ORG*) processing.
    #
    #   vNOTE=$( echo "${LINE}" | tr -d '|' | tr ' ' ';' | awk -F ':' '{print $2}' )
    #   if [ -z ${vNOTES} ]
    #   then
    #     vNOTES="${vNOTE}"
    #   else
    #     vNOTES="${vNOTES};${vNOTE}"
    #   fi
    #   vNOTE=""
    #   ;;
    
    
    (NOTE*|ORG*)
      vNOTE=$( echo "${LINE}" | tr -d '|' | sed -e "s+;+~;+g" -e "s+ +;+g" | awk -F ':' '{print $2}' )
      if [ -z ${vNOTES} ]
      then
        vNOTES="${vNOTE}"
      else
        vNOTES="${vNOTES}~;${vNOTE}"
      fi
      ;;
```

And in `contacts-convert-vcf-to.sh`. First replace tilde-escaped-semicolons with a temporary string without semicolons; then replace remaining semicolons with spaces and the reset the temporary strings with single semicolons:
```
    # NOTES
    if [ "x${vNOTE}" != "x-" ]
    then
      # echo "NOTE:${vNOTE}" 
      echo "NOTE:${vNOTE}" | sed -e "s+~\;+~~~+g" -e "s+\;+ +g" -e "s+~~~+;+g"
    fi
```

**Comment by vermaden** [comment]
Hi,

I need to ask You something - there were many messages/replies/requests from your side - and I believe after all of them - I just lost track what improvements and where should be done ...

Lets do it the 'oldschool' way - please send me these 'fixed' or 'modifed' scripts with all improvements made as attachments to email - to ''vermaden [AT] interia [DOT] pl'' address - thanks :)

Regards,
ver

**Comment by pe1aqp** [comment]
Mostly taken-up in the "UTF-8" flavour of the vcf scripts.
Some further developments can be found on: [my web-site](http://pe1aqp.krom.eu/software/vcf-handling/)
