### ISSUE TITLE
lsblk.sh errors

### ISSUE THREAD

**Issue by ghost** [vermaden/scripts#2]
Freebsd 12.1 beta1

![2019-10-01-154950_1660x1006_scrot](https://user-images.githubusercontent.com/980/65995259-1d8a2a00-e463-11e9-8273-8141761e2424.png)

**Comment by vermaden** [comment]
Thank you for submitting this, new lsblk.sh version is on its way.Regards,vermadenOd: "gregf" &lt;notifications@github.com&gt;Do: "vermaden/scripts" &lt;scripts@noreply.github.com&gt;; Wysłane: 21:50 Wtorek 2019-10-01Temat: [vermaden/scripts] lsblk.sh errors (#2)Freebsd 12.1 beta1

**Comment by vermaden** [comment]
Nice prompt/terminal/tmux/screen BTW :)

**Comment by ghost** [comment]
The prompt is [starlight](https://github.com/starship/starship) tmux theme is [nord-tmux](https://github.com/arcticicestudio/nord-tmux) and the theme is [nord](https://github.com/arcticicestudio/nord)

**Comment by vermaden** [comment]
Please try latest version and report how it behaves:
https://raw.githubusercontent.com/vermaden/scripts/master/lsblk.sh

**Comment by ghost** [comment]
@vermaden All fixed up now, thanks!

**Comment by vermaden** [comment]
Welcome :)
