### ISSUE TITLE
dzen2-update.sh references non-existent battery script

### ISSUE THREAD

**Issue by ppenzin** [vermaden/scripts#9]
https://github.com/vermaden/scripts/blob/be75c60e57e13ef171a83da798f8fb00e2c245c5/dzen2-update.sh#L73

`__conky_battery_separate.sh` doesn't exist in this repo, only `__conky_battery.sh`.

**Comment by vermaden** [comment]
Added.

Here:
https://github.com/vermaden/scripts/blob/master/__conky_battery_separate.sh

Regards.

**Comment by ppenzin** [comment]
Thanks!
